### ISSUE TITLE
Image for missing sample missing...

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/gens#19]
![Screenshot 2022-12-12 at 16 18 45](https://user-images.githubusercontent.com/758570/207082873-2f7d43f9-5cea-44d6-a69b-7284da15e64e.png)

**Comment by raysloks** [comment]
Seems like removing the extra `/` from `/static//svg/broken-dna.svg` allows it to find the image.
However, it becomes very big, which appears to be because the stylesheet url `/static//css/error.min.css` also has an extra `/`.
Will try to find where this extra `/` is introduced.

**Comment by raysloks** [comment]
Some of the templates have a leading `/`:
https://github.com/Clinical-Genomics/gens/blob/master/gens/templates/sample_not_found.html#L7
while others do not:
https://github.com/Clinical-Genomics/gens/blob/master/gens/blueprints/gens/templates/gens.html#L19
The ones missing the leading `/` appear to be working correctly.
I think I'll make a PR that removes the leading slashes
