### ISSUE TITLE
Adding tracks to aid analysis with GENS

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/gens#35]
As previously discussed at the meeting 12/9 we would like to improve the analysis of SVs using both GENS and vcf2cytosure. When it comes to GENS we would like to add a track with common CNVs (data from our clinical array-cgh database). Gains should be colored blue or possibly green and losses should be red. It should also be possible to see the frequency (provided in the attached file).
[Final_common_CNV_clusters_0.9_jaccard_0.002_freq_adusted_211207.txt](https://github.com/Clinical-Genomics/scout/files/12748548/Final_common_CNV_clusters_0.9_jaccard_0.002_freq_adusted_211207.txt)

**Comment by dnil** [comment]
Overlaps issue #25, but good info, and perhaps better like this for prioritisation.

**Comment by raysloks** [comment]
Hey, sorry for taking so long with this.

Some minor issues:
* Annotation tracks are currently global, which I think was mentioned at the meeting.
* Had to add the default annotation track "databaseExport_220512", otherwise the dropdown menu wouldn't work. I uploaded a dummy version of it.
* Gens currently only cares about a select few .bed-columns when loading annotations, so I elected to merge Gain/Loss and Freq into Name.

I've uploaded the file with its name as is, but any name not containing a . should work iirc.

**Comment by dnil** [comment]
> Hey, sorry for taking so long with this.

Thank you! Life is life; priorities eh!

> Some minor issues:
> 
> * Annotation tracks are currently global, which I think was mentioned at the meeting.

Thats fine, may be something we need to think about when the balsamic crew wants more cases, but for now all good.

> * Had to add the default annotation track "databaseExport_220512", otherwise the dropdown menu wouldn't work. I uploaded a dummy version of it.

Right, we specify it here: https://github.com/Clinical-Genomics/servers/blob/518e790ffcbded1bd2a8c0c053e99d9615bbd48c/config/CGVS/config/app/cg-prod-services.scilifelab.se/gens.conf.py#L8

Perhaps this cluster track is a better starting point for now; we could switch the default for it on the servers repo. 

> * Gens currently only cares about a select few .bed-columns when loading annotations, so I elected to merge Gain/Loss and Freq into Name.

Good call, and with the color rename. We can think about extending that, but one thing at the time.

> I've uploaded the file with its name as is, but any name not containing a . should work iirc.

Ping to @alieden to see if he has a good alias? "Common_CNV_clusters_211207"?

Looks all good otw; please document somewhere, either in Atlas, or in a PR here, then perhaps including a small script to do the bed-file color preprocessing plus commands to load to stage and prod to local docs. Dunno, something like:
 
On hasta, activate the gens stage env and load your processed bed file:
```
conda activate S_gens
gens load annotations -f my_processed_bed.bed -b 37`
```
If all tests look nominal on the gens stage server, load to production.
```
conda activate P_gens
gens load annotations -f my_processed_bed.bed -b 37`
```

**Comment by dnil** [comment]
Some docs have been added to the readme with #49, and prod tracks loaded.
