### ISSUE TITLE
Include recent updates from Lund repo?

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/gens#39]
It seems that there have been quite a lot of activity on Lunds GENS repo, new features and bugfixes maybe that could be nice to add. Including for instance the recent request I made here: https://github.com/Clinical-Genomics/gens/issues/38

Maybe it would be worth to check if we could include some of their changes in our version : ) 
https://github.com/Clinical-Genomics-Lund/gens/issues

**Comment by raysloks** [comment]
Took a quick look at this. There doesn't seem to be any major conflicts with the changes we've made, so it should be relatively straightforward.

**Comment by dnil** [comment]
All good, closed with #42. And we have discussed with Lund to review and test our (@raysloks, mostly😸) additions on this repo to see if we couldn't just merge the repos to avoid the double trouble.
