### ISSUE TITLE
Pan can exit chromosome.. 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/gens#56]
chromosome size end of window is not respected, even though `drawTrack` is supposed to call `limitRegionToChromosome` - some `async` issue perhaps?

**Comment by raysloks** [comment]
I think it might be due to https://github.com/Clinical-Genomics/gens/blob/145aed2792b674fac16e5c5790882f871dbb99e3/assets/js/navigation.js#L101 not passing on genomeBuild which then defaults to '38', possibly causing it to fetch incorrect values or null.
