### ISSUE TITLE
Easier way to delete samples

### ISSUE THREAD

**Issue by raysloks** [Clinical-Genomics/gens#71]
As discussed in https://github.com/Clinical-Genomics/cg/issues/3197, it'd be good to have an easier method for deleting samples a la `gens delete sample`.

Once implemented in Gens, it'd probably be prudent to add a corresponding command to cg.

**Comment by mathiasbio** [comment]
I would love this feature! It would be so nice to have when developing the bioinformatics to be uploaded to gens, to be able to test changes to the coverage profile for instance with PON, without PON etc on the same sample 🌟

**Comment by raysloks** [comment]
I accidentally committed straight to master (we should disable our ability to do that), but this has been implemented now.
The `--force` flag on `gens load sample` should be enough for most use cases, but this is still very good to have.

Test successful on stage:
```
[emil.bertilsson@hasta:~] [S_gens] $ gens load sample --force -i testSample2 -b 37 -a /home/emil.bertilsson/ACC3005A2_lanes_22_sorted_md.baf.bed.gz -c /home/emil.bertilsson/ACC3005A2_lanes_22_sorted_md.cov.bed.gz -n testCase
[2024-07-08 11:47:55,234] INFO in db: Initialize db connection
[2024-07-08 11:47:55,387] INFO in samples: Store sample "testSample2" in database
[2024-07-08 11:47:55,395] ERROR in samples: Sample with sample_id="testSample2" and case_id="testCase" was overwritten.
Finished adding a new sample to database ✔
[emil.bertilsson@hasta:~] [S_gens] $ gens delete sample -i testSample2 -b 37 -n testCase
[2024-07-08 11:48:33,769] INFO in db: Initialize db connection
[2024-07-08 11:48:33,960] INFO in samples: Store sample "testSample2" in database
Finished removing a sample from database ✔
[emil.bertilsson@hasta:~] [S_gens] $ gens load sample --force -i testSample2 -b 37 -a /home/emil.bertilsson/ACC3005A2_lanes_22_sorted_md.baf.bed.gz -c /home/emil.bertilsson/ACC3005A2_lanes_22_sorted_md.cov.bed.gz -n testCase
[2024-07-08 11:48:49,923] INFO in db: Initialize db connection
[2024-07-08 11:48:50,098] INFO in samples: Store sample "testSample2" in database
Finished adding a new sample to database ✔
[emil.bertilsson@hasta:~] [S_gens] $ 
```
And deployed to prod as well.

But now I noticed that it logs `[2024-07-08 11:48:33,960] INFO in samples: Store sample "testSample2" in database` when deleting a sample.

**Comment by mathiasbio** [comment]
Nice! 🥳 🥳 🥳
