### ISSUE TITLE
Track is missing exons in SMARCB1 gene?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/gens#84]
**Describe the bug**
Hi, I don't know if it's a bug, but looks like some exons are not visible on the gene track?
Check out [this user ticket](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=71554)

**To Reproduce**
1. Go to the following variant: https://scout.scilifelab.se/cust002/F0062814/sv/variants/13ab363d0876f34a97ea595a51bf5702
2. Open it on IGV and notice that it hits exons 6 of the gene:

![image](https://github.com/user-attachments/assets/eacecee2-f06f-437c-a23b-77db234d3049)

But gens shows only exons 1-5:

<img width="1610" alt="image" src="https://github.com/user-attachments/assets/1ca4eadd-0bc4-43ab-8b4d-e135eea134c2">

**Comment by northwestwitch** [comment]
FYI @terestahl

**Comment by raysloks** [comment]
I think I've found it, but it was definitely more challenging than it should be.
<img width="1440" alt="Screenshot 2024-07-19 at 09 21 27" src="https://github.com/user-attachments/assets/a55af7d8-1ed9-4632-ab13-5f4e7e24173c">
First I had to expand the track with right click, and then I had to hover over many markers until I found it.

If you'd like to, I can make an issue for improving Gens' usability in this manner. Perhaps adding an expand-button and/or adding the exon number to the display name of the transcript?

**Comment by terestahl** [comment]
Yes please, do so. But also it should be the longest transcript that is showed by default In the collapsed genes track and not the shortest one as it is now  which can lead to misunderstanding
Thanks!

Teresita Díaz de Ståhl, PhD., Assoc. Prof.
Department of Oncology-Pathology
Cancer Center Karolinska, CCK R8:04
Karolinska Institutet
SE-171 76 Stockholm, Sweden
+46-8-517 721 35 (office)
E-mail:  ***@***.***<https://email.ki.se/owa/redir.aspx?C=4BufL_Koh06XApJTXHLne_SR0tGstdEIBMXUIai5m0M3Lus3DSi31dFbBzEDctNC36TEzjRWsIg.&URL=mailto%3aTeresita.Diaz.de.Stahl%40ki.se>

**Comment by northwestwitch** [comment]
> Yes please, do so. But also it should be the longest transcript that is showed by default In the collapsed genes track and not the shortest one as it is now which can lead to misunderstanding Thanks!

Ah OK you answered, I was also about to suggest to do so :)

**Comment by raysloks** [comment]
Alright, I have created the issues. However, I will not personally be able to work on them until I return from vacation in around 3 weeks.

**Comment by northwestwitch** [comment]
> Alright, I have created the issues. However, I will not personally be able to work on them until I return from vacation in around 3 weeks.

That's great. Enjoy the holidays! 🍹 🌴
